### ISSUE TITLE
Create wish not added to wishlist until refresh

### ISSUE THREAD

**Issue by kfrancois** [kfrancois/wishlist#32]

**Comment by PrebenLeroy** [comment]
``protected async override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            WishList = await wishListService.GetWishlist(((Wishlist)e.Parameter).WishlistId);
            PageHeader.Text = WishList.Title;
            Wishes = new ObservableCollection<Wish>(WishList.Wishes);
            ListView1.ItemsSource = Wishes;
        }``
